@startuml

| Coffee |
start
| Farmer |
:harvestItem();
:processItem();
:packItem();
:addItem();
| Distributor |
:buyItem();
:shipItem();
| Retailer |
:receiveItem();
| Consumer |
:fetchItem();
stop
@enduml