@startuml

participant Coffee as coffee
participant Farmer as farmer
participant Distributor as distributor
participant Retailer as retailer
participant Consumer as consumer

activate coffee
activate farmer
farmer->coffee: harvestItem()
farmer->coffee: processItem()
farmer->coffee: packItem()
farmer->coffee: addItem()
distributor->farmer: buyItem()
deactivate farmer
activate distributor
distributor->retailer: shipItem()
activate retailer
retailer->distributor: receiveItem()
deactivate distributor
activate consumer
consumer->retailer: purchaseItem()
deactivate retailer
coffee->consumer: fetchItem()
@enduml